Repository jac-uk/admin, pull requests merged in 2021-09, with the labels that each got.

#1357 Feature/1327 enable request of character check form completion
  src/components/CharacterChecks/CharacterChecks.vue
  src/components/CharacterChecks/OtherProfessionalBodies.vue
  src/components/ModalViews/CharacterChecksRequests.vue
  src/store.js
  src/store/characterChecks/characterChecks.js
  src/views/CreateExercise.vue
  src/views/Exercise/Applications/AgencyReport.vue
  src/views/Exercise/Applications/Application.vue
  src/views/Exercise/Tasks/CharacterChecks.vue
  src/views/InformationReview/FinancialMattersAgencyReport.vue
Labels: Ready to play

#1453 #589 Implement firebase app check
  .env.develop
  .env.production
  .env.staging
  .env.test
  .github/workflows/manual-deploy.yml
  .github/workflows/on-merge.yml
  .github/workflows/on-pull-request.yml
  .github/workflows/on-release.yml
  package-lock.json
  package.json
  src/firebase.js
Labels: Frozen by Matt

#1331 #1314/additonal legal experience
  src/views/Exercise/Applications/Application.vue
Labels: Frozen by Matt, Needs Changes After PR
