Repository jac-uk/admin, pull requests merged in 2023-12, with the labels that each got.

#2215 #2159 Disallow archiving until exercise unpublished from website
  src/App.vue
  src/store/exercise/document.js
  src/views/Exercise.vue
  src/views/Exercise/Details/Overview/ApprovalProcess.vue
  src/views/Exercise/Details/Summary/View.vue
  src/views/Exercises.vue
Labels: Passed UT

#2136 #2091/self assessment document extraction
  package-lock.json
  src/components/RepeatableFields/SelfAssessmentSection.vue
  src/views/Exercise/Details/Assessments/Edit.vue
  src/views/Exercise/Details/Assessments/View.vue
  src/views/InformationReview/AssessmentsSummary.vue
Labels: Needs UT

#2244 #2173 Independent Assessments
  src/components/ModalViews/IndependentAssessmentsRequests.vue
Labels: Passed UT

#2236 Feature/2161 Changing Live Exercises page to display exercise status and stage
  src/views/Exercises.vue
Labels: Passed UT

#2117 #2095 issue ticketing system
  package-lock.json
  package.json
  src/App.vue
  src/assets/remove.png
  src/assets/screenshot.png
  src/components/Feedback/FeedbackForm.vue
  src/components/Feedback/UserFeedbackLink.vue
  src/components/Micro/CaptureScreenshot.vue
  src/components/ModalViews/UserFeedbackModal.vue
  src/store.js
  src/store/auth.js
  src/store/bugReports/collection.js
  src/store/bugReports/document.js
  vite.config.js
Labels: Needs Internal UT

#2264 Fixed an error in candidate submission due to there being no screensh…
  src/components/Feedback/FeedbackForm.vue
Labels: Needs Internal UT

#2268 #2265 Redirect to next page on sign in
  src/main.js
  src/router.js
Labels: Needs UT

#2222 Epic #2141 Embedding Pre-Selection Day Questionnaires on the Platform
  src/App.vue
  src/components/ModalViews/CandidateFormNotification.vue
  src/components/Page/ProgressBar.vue
  src/filters.js
  src/helpers/constants.js
  src/helpers/exerciseHelper.js
  src/helpersTMP/Timeline/exerciseTimeline.js
  src/permissions.js
  src/router.js
  src/store.js
  src/store/candidateForms/document.js
  src/store/candidateForms/records.js
  src/views/Exercise/Details/Timeline/Edit.vue
  src/views/Exercise/Tasks/Task/CandidateForm/Configure.vue
  src/views/Exercise/Tasks/Task/CandidateForm/LocationDate.vue
  src/views/Exercise/Tasks/Task/CandidateForm/Monitor.vue
  src/views/Exercise/Tasks/Task/Completed.vue
  src/views/Exercise/Tasks/Task/New/default.vue
Labels: Passed UT
