Repository jac-uk/admin, pull requests merged in 2024-07, with the labels that each got.

#2465 #2428 Admin refresh - Improvements to Exercises Live page
  package-lock.json
  package.json
  src/App.vue
  src/views/Candidates/Candidates.vue
  src/views/Exercises.vue
  src/views/Panellists/List.vue
Labels: Passed UT

#2489 Feature/2406 Generate basic programme Gantt chart view
  package-lock.json
  package.json
  src/App.vue
  src/components/Timeline.vue
  src/router.js
  src/views/ExercisesProgrammeView.vue
  tests/unit/components/Timeline.spec.js
Labels: Needs Internal UT

#2480 Feature/2429 test navigation improvements
  package-lock.json
  package.json
  src/App.vue
  src/components/Navigation/FullWidthMenu.vue
  src/components/Navigation/TabMenu1.vue
  src/components/Navigation/TabMenu2.vue
  src/composables/useExercise.js
  src/views/Exercise.vue
  src/views/Exercise/Details.vue
Labels: Needs UT, Needs Internal UT
